# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=50)),
                ('description_item', models.CharField(max_length=50)),
                ('price_item', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity_item', models.IntegerField()),
                ('type_item', models.BooleanField(default=True)),
                ('id_item', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description_restaurant', models.CharField(max_length=100)),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('tables', models.IntegerField()),
                ('is_ready', models.BooleanField(default=False)),
            ],
        ),
    ]
