# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_drink_map_food_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=50)),
                ('description_item', models.CharField(max_length=50)),
                ('price_item', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity_item', models.IntegerField(max_length=50)),
                ('type_item', models.BooleanField(default=True)),
                ('id_item', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Drink_Map',
        ),
        migrations.DeleteModel(
            name='Food_Menu',
        ),
    ]
