# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20170225_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='quantity_item',
            field=models.IntegerField(),
        ),
    ]
