# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=220)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=256)),
                ('ime', models.CharField(max_length=220)),
                ('prezime', models.CharField(max_length=220)),
            ],
        ),
    ]
