# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='activation_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
